version: "3.8"
services:
  event-system-fe:
    build: ./calendar-client
    container_name: calendar_fe_c
    ports:
      - "3000:3000"
    volumes:
      - ./app
      - ./app/node_modules
    stdin_open: true
    tty: true