version: "3.8"
services:
  calendar-client:
    build: ./calendar-client
    container_name: calendar_fe
    ports:
      - "3000:3000"
    volumes:
      - ./calendar-client/app
      - ./calendar-client/app/node_modules
    stdin_open: true
    tty: true
