version: "3.8"
services:
  calendar-client:
    build: ./calendar-client
    container_name: calendar_fe
    ports:
      - "3000:3000"
    volumes:
      - ./calendar-client/app
      - ./calendar-client/app/node_modules
    stdin_open: true
    tty: true
  calendar-server:
    build: ./calendar-server
    container_name: calendar_be
    ports:
      - "3000:3000"
    volumes:
      - ./calendar-server/app
      - ./calendar-server/app/node_modules
    stdin_open: true
    tty: true
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
