version: "3.8"
services:
  calendar-client:
    build: ./calendar-client
    container_name: calendar_fe
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - calendar-server
  calendar-server:
    build: ./calendar-server
    container_name: calendar_be
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./events:/data/db
    ports:
      - "27017:27017"
